<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html lang="en" >
<head>
	<meta charset="UTF-8">
	<title>Carousel Slider With Autoplay + Hover Pause</title>
	<link rel="stylesheet" href="./style.css">

	<style>
/* ----------------------------------------------
 * Generated by Animista on 2024-4-17 10:13:44
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation scale-up-hor-center
 * ----------------------------------------
 */
@-webkit-keyframes scale-up-hor-center {
  0% {
    -webkit-transform: scaleX(0.4);
            transform: scaleX(0.4);
  }
  100% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
  }
}
@keyframes scale-up-hor-center {
  0% {
    -webkit-transform: scaleX(0.4);
            transform: scaleX(0.4);
  }
  100% {
    -webkit-transform: scaleX(1);
            transform: scaleX(1);
  }
}

	</style>
</head>
<body>
	<p style="text-align: center; font-size: 45px; font-weight: bolder;" class="scale-up-hor-center ">WELCOME TO HOTEL VILLA's</p>
<div id="Carousel-slider" >
	<section style="display: flex; ">
		<div class="Carousel-slider">
			<!-- Background Images div -->
			<div class="slider-item superHero1" data-href="#" ></div>
			<div class="slider-item superHero2" data-href="#" ></div>
			<div class="slider-item superHero3" data-href="#" ></div>
			<div class="slider-item superHero4" data-href="#" ></div> 
			 <div class="slider-item superHero5" data-href="#" ></div>
			<div class="slider-item superHero6" data-href="#" ></div>
			<div class="slider-item superHero7" data-href="#" ></div>
			<!-- Background Images div End -->
		</div>	
	</section>
	<div class="logo_div" style="width: 100%; height: 90px; display: flex; margin-bottom: 0px; margin-top: 0%;">
		<div>
			<a href="HotelRegisterLogin.jsp"><img src="Hotel_Logo.png" alt="" height="85px" width="200px" style="margin-left: 530px;"></a>
		</div>
		<div>
			<a href="CustomerRegisterLogin.jsp"><img src="Customer_logo.png" alt="" height="85px" width="200px" style="margin-left: 100px;"></a>
		</div>
	</div>
</div>



<script src="https://cdnjs.cloudflare.com/ajax/libs/hammer.js/2.0.8/hammer.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/micro-slider@1.0.9/dist/micro-slider.min.js"></script>
<script  src="style.js"></script>

</body>
</html>